### ISSUE TITLE
集成后无法运行，报错：java.lang.RuntimeException: Unable to instantiate application .app.MyTinkerApplication: java.lang.InstantiationException: class .app.MyTinkerApplication has no zero argument constructor

### ISSUE THREAD

**Issue by Sky-Walkrr** [BuglyDevTeam/Bugly-Android-Demo#1]
按照bugly文档集成bugly update SDK后，build成功，但应用无法启动，报错：java.lang.RuntimeException: Unable to instantiate application 
.app.MyTinkerApplication: java.lang.InstantiationException: class 
app.MyTinkerApplication has no zero argument constructor。
log:
> java.lang.RuntimeException: Unable to instantiate application 
.app.MyTinkerApplication: java.lang.InstantiationException: class 
.app.MyTinkerApplication has no zero argument constructor
    at android.app.LoadedApk.makeApplication(LoadedApk.java:563)
    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4636)
    at android.app.ActivityThread.access$1500(ActivityThread.java:160)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1428)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:135)
    at android.app.ActivityThread.main(ActivityThread.java:5371)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1125)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:809)
 Caused by: java.lang.InstantiationException: class .app.MyTinkerApplication has no zero argument constructor
    at java.lang.Class.newInstance(Class.java:1597)
    at android.app.Instrumentation.newApplication(Instrumentation.java:995)
    at android.app.Instrumentation.newApplication(Instrumentation.java:980)
    at android.app.LoadedApk.makeApplication(LoadedApk.java:558)
    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4636) 
    at android.app.ActivityThread.access$1500(ActivityThread.java:160) 
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1428) 
    at android.os.Handler.dispatchMessage(Handler.java:102) 
    at android.os.Looper.loop(Looper.java:135) 
    at android.app.ActivityThread.main(ActivityThread.java:5371) 
    at java.lang.reflect.Method.invoke(Native Method) 
    at java.lang.reflect.Method.invoke(Method.java:372) 
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1125) 
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:809) 
 Caused by: java.lang.NoSuchMethodException: <init> []
    at java.lang.Class.getConstructor(Class.java:531)
    at java.lang.Class.getDeclaredConstructor(Class.java:510)
    at java.lang.Class.newInstance(Class.java:1595)
    at android.app.Instrumentation.newApplication(Instrumentation.java:995) 
    at android.app.Instrumentation.newApplication(Instrumentation.java:980) 
    at android.app.LoadedApk.makeApplication(LoadedApk.java:558) 
    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4636) 
    at android.app.ActivityThread.access$1500(ActivityThread.java:160) 
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1428) 
    at android.os.Handler.dispatchMessage(Handler.java:102) 
    at android.os.Looper.loop(Looper.java:135) 
    at android.app.ActivityThread.main(ActivityThread.java:5371) 
    at java.lang.reflect.Method.invoke(Native Method) 
    at java.lang.reflect.Method.invoke(Method.java:372) 
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1125) 
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:809)

**Comment by Sky-Walkrr** [comment]
之前单独集成tinker成功（用的注解方式）。目前项目也引用了bugly，所以统一用bugly的hotfix，但按文档集成后出现上面的问题，请问如何解决？

**Comment by TencentBugly** [comment]
你好！请问您的QQ是多少？我拉程序员帮您看看！


发件人: Sky-Walkrr [mailto:notifications@github.com]
发送时间: 2016年11月30日,星期三 16:33
收件人: BuglyDevTeam/Bugly-Android-Demo
主题: [BuglyDevTeam/Bugly-Android-Demo] java.lang.RuntimeException: Unableto instantiate application cn.madeapps.android.jyq.app.MyTinkerApplication:java.lang.InstantiationException: classcn.madeapps.android.jyq.app.MyTinkerApplication has no zero argumentco...


按照bugly文档集成bugly update SDK后，build成功，但应用无法启动，报错：java.lang.RuntimeException: Unable to instantiate application cn.madeapps.android.jyq.app.MyTinkerApplication: java.lang.InstantiationException: class cn.madeapps.android.jyq.app.MyTinkerApplication has no zero argument constructor。
log:

java.lang.RuntimeException: Unable to instantiate application cn.madeapps.android.jyq.app.MyTinkerApplication: java.lang.InstantiationException: class cn.madeapps.android.jyq.app.MyTinkerApplication has no zero argument constructor
at android.app.LoadedApk.makeApplication(LoadedApk.java:563)
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4636)
at android.app.ActivityThread.access$1500(ActivityThread.java:160)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1428)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5371)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1125)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:809)
Caused by: java.lang.InstantiationException: class cn.madeapps.android.jyq.app.MyTinkerApplication has no zero argument constructor
at java.lang.Class.newInstance(Class.java:1597)
at android.app.Instrumentation.newApplication(Instrumentation.java:995)
at android.app.Instrumentation.newApplication(Instrumentation.java:980)
at android.app.LoadedApk.makeApplication(LoadedApk.java:558)
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4636)
at android.app.ActivityThread.access$1500(ActivityThread.java:160)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1428)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5371)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1125)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:809)
Caused by: java.lang.NoSuchMethodException: []
at java.lang.Class.getConstructor(Class.java:531)
at java.lang.Class.getDeclaredConstructor(Class.java:510)
at java.lang.Class.newInstance(Class.java:1595)
at android.app.Instrumentation.newApplication(Instrumentation.java:995)
at android.app.Instrumentation.newApplication(Instrumentation.java:980)
at android.app.LoadedApk.makeApplication(LoadedApk.java:558)
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4636)
at android.app.ActivityThread.access$1500(ActivityThread.java:160)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1428)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5371)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1125)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:809)

**Comment by devilWwj** [comment]
HI，看错误日志是你的Application配置出错了，我们建议你自定义TinkerApplication，而不是使用注解方式，具体查看我们的集成文档：https://bugly.qq.com/docs/user-guide/instruction-manual-android-hotfix/?v=20161130212726
