### ISSUE TITLE
StrictMode检测到bugly网络请求没有关闭

### ISSUE THREAD

**Issue by g19980115** [BuglyDevTeam/Bugly-Android-Demo#114]
日志如下：
```Java
StrictMode: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
    java.lang.Throwable: Explicit termination method 'close' not called
        at dalvik.system.CloseGuard.open(CloseGuard.java:180)
        at java.io.FileInputStream.<init>(FileInputStream.java:147)
        at com.tencent.bugly.proguard.ac.c(BUGLY:203)
        at com.tencent.bugly.proguard.ac.b(BUGLY:87)
        at com.tencent.bugly.proguard.ac.b(BUGLY:29)
        at com.tencent.bugly.proguard.ac$2.run(BUGLY:258)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
```

**Comment by g19980115** [comment]
又发现了一个：
```Java
E/StrictMode: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
    java.lang.Throwable: Explicit termination method 'close' not called
        at dalvik.system.CloseGuard.open(CloseGuard.java:180)
        at java.util.zip.ZipFile.<init>(ZipFile.java:230)
        at java.util.zip.ZipFile.<init>(ZipFile.java:147)
        at java.util.jar.JarFile.<init>(JarFile.java:161)
        at java.util.jar.JarFile.<init>(JarFile.java:125)
        at com.tencent.bugly.beta.tinker.TinkerUtils.readJarEntry(BUGLY:302)
        at com.tencent.bugly.beta.tinker.TinkerManager.checkNewPatch(BUGLY:477)
        at com.tencent.bugly.beta.tinker.TinkerManager.applyPatch(BUGLY:431)
        at com.tencent.bugly.beta.tinker.TinkerManager.onDownloadSuccess(BUGLY:409)
        at com.tencent.bugly.beta.download.a.onCompleted(BUGLY:203)
        at com.tencent.bugly.beta.global.d.run(BUGLY:263)
        at android.os.Handler.handleCallback(Handler.java:836)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:203)
        at android.app.ActivityThread.main(ActivityThread.java:6251)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)
```
