### ISSUE TITLE
接入crashreport_upgrade:1.3.6'，编译出现Error: Type com.tencent.bugly.proguard.t is referenced as an interface from `com.tencent.bugly.crashreport.crash.b$1`.

### ISSUE THREAD

**Issue by Leelion96** [BuglyDevTeam/Bugly-Android-Demo#148]
#### 异常类型

接入接入crashreport_upgrade:1.3.6'之后，编译出现
`Error: Type com.tencent.bugly.proguard.t is referenced as an interface from'com.tencent.bugly.crashreport.crash.b$1'.`
和
`Caused by: com.android.tools.r8.utils.AbortException: Error: Type com.tencent.bugly.proguard.ar is referenced as an interface from `com.tencent.bugly.proguard.at`. 等错误  

#### Tinker版本
`com.tencent.bugly:tinker-support:1.1.1`
`com.tencent.bugly:nativecrashreport:3.6.0.1`
`com.tencent.bugly:crashreport_upgrade:1.3.6`
#### gradle版本
3.2.0

#### 系统
Mac

#### 堆栈/日志

lis-Mac-mini:AgentBear leelion6$ gradle assembleDebug --stacktrace
D8: InnerClass annotations are missing corresponding EnclosingMember annotations. Such InnerClass annotations are ignored.
D8: InnerClass annotations are missing corresponding EnclosingMember annotations. Such InnerClass annotations are ignored.
JarCode: JSR encountered; reparse using JSRInlinerAdapter
D8: InnerClass annotations are missing corresponding EnclosingMember annotations. Such InnerClass annotations are ignored.
D8: InnerClass annotations are missing corresponding EnclosingMember annotations. Such InnerClass annotations are ignored.
JarCode: JSR encountered; reparse using JSRInlinerAdapter
D8: InnerClass annotations are missing corresponding EnclosingMember annotations. Such InnerClass annotations are ignored.
D8: InnerClass annotations are missing corresponding EnclosingMember annotations. Such InnerClass annotations are ignored.
D8: InnerClass annotations are missing corresponding EnclosingMember annotations. Such InnerClass annotations are ignored.
D8: InnerClass annotations are missing corresponding EnclosingMember annotations. Such InnerClass annotations are ignored.
D8: InnerClass annotations are missing corresponding EnclosingMember annotations. Such InnerClass annotations are ignored.
D8: InnerClass annotations are missing corresponding EnclosingMember annotations. Such InnerClass annotations are ignored.
D8: InnerClass annotations are missing corresponding EnclosingMember annotations. Such InnerClass annotations are ignored.
D8: InnerClass annotations are missing corresponding EnclosingMember annotations. Such InnerClass annotations are ignored.
/Users/leelion6/Documents/work space/AgentBear/app/build/intermediates/transforms/appJoint/debug/120.jar: D8: Type `com.tencent.tinker.lib.reporter.DefaultPatchReporter` was not found, it is required for default or static interface methods desugaring of `void com.tencent.bugly.beta.tinker.TinkerPatchReporter.onPatchServiceStart(android.content.Intent)`
/Users/leelion6/Documents/work space/AgentBear/app/build/intermediates/transforms/appJoint/debug/120.jar: D8: Type `com.tencent.tinker.lib.util.UpgradePatchRetry` was not found, it is required for default or static interface methods desugaring of `void com.tencent.bugly.beta.tinker.TinkerPatchReporter.onPatchServiceStart(android.content.Intent)`
/Users/leelion6/Documents/work space/AgentBear/app/build/intermediates/transforms/appJoint/debug/120.jar: D8: Type `com.tencent.tinker.lib.util.TinkerLog` was not found, it is required for default or static interface methods desugaring of `void com.tencent.bugly.beta.tinker.TinkerResultService.restartProcess()`
/Users/leelion6/Documents/work space/AgentBear/app/build/intermediates/transforms/appJoint/debug/120.jar: D8: Type `com.tencent.tinker.lib.util.TinkerServiceInternals` was not found, it is required for default or static interface methods desugaring of `void com.tencent.bugly.beta.tinker.TinkerResultService.onPatchResult(com.tencent.tinker.lib.service.PatchResult)`
/Users/leelion6/Documents/work space/AgentBear/app/build/intermediates/transforms/appJoint/debug/120.jar: D8: Type `com.tencent.tinker.lib.util.UpgradePatchRetry` was not found, it is required for default or static interface methods desugaring of `boolean com.tencent.bugly.beta.tinker.TinkerLoadReporter$1.queueIdle()`
/Users/leelion6/Documents/work space/AgentBear/app/build/intermediates/transforms/appJoint/debug/120.jar: D8: Type `com.tencent.tinker.lib.tinker.TinkerApplicationHelper` was not found, it is required for default or static interface methods desugaring of `void com.tencent.bugly.beta.tinker.TinkerUncaughtExceptionHandler.tinkerPreVerifiedCrashHandler(java.lang.Throwable)`
/Users/leelion6/Documents/work space/AgentBear/app/build/intermediates/transforms/appJoint/debug/120.jar: D8: Type `com.tencent.tinker.loader.shareutil.ShareTinkerInternals` was not found, it is required for default or static interface methods desugaring of `void com.tencent.bugly.beta.tinker.TinkerUncaughtExceptionHandler.tinkerPreVerifiedCrashHandler(java.lang.Throwable)`
/Users/leelion6/Documents/work space/AgentBear/app/build/intermediates/transforms/appJoint/debug/120.jar: D8: Type `com.tencent.tinker.lib.listener.DefaultPatchListener` was not found, it is required for default or static interface methods desugaring of `int com.tencent.bugly.beta.tinker.TinkerPatchListener.patchCheck(java.lang.String, java.lang.String)`
/Users/leelion6/Documents/work space/AgentBear/app/build/intermediates/transforms/appJoint/debug/120.jar: D8: Type `com.tencent.tinker.loader.shareutil.SharePatchFileUtil` was not found, it is required for default or static interface methods desugaring of `int com.tencent.bugly.beta.tinker.TinkerPatchListener.patchCheck(java.lang.String, java.lang.String)`
/Users/leelion6/Documents/work space/AgentBear/app/build/intermediates/transforms/appJoint/debug/120.jar: D8: Type `com.tencent.tinker.lib.reporter.DefaultLoadReporter` was not found, it is required for default or static interface methods desugaring of `void com.tencent.bugly.beta.tinker.TinkerLoadReporter.onLoadPatchListenerReceiveFail(java.io.File, int)`
/Users/leelion6/Documents/work space/AgentBear/app/build/intermediates/transforms/appJoint/debug/120.jar: D8: Type `com.tencent.tinker.lib.util.TinkerLog` was not found, it is required for default or static interface methods desugaring of `void com.tencent.bugly.beta.tinker.TinkerLoadReporter.onLoadFileNotFound(java.io.File, int, boolean)`
/Users/leelion6/Documents/work space/AgentBear/app/build/intermediates/transforms/appJoint/debug/120.jar: D8: Type `com.tencent.tinker.lib.tinker.Tinker` was not found, it is required for default or static interface methods desugaring of `void com.tencent.bugly.beta.tinker.TinkerLoadReporter.onLoadFileNotFound(java.io.File, int, boolean)`
/Users/leelion6/Documents/work space/AgentBear/app/build/intermediates/transforms/appJoint/debug/120.jar: D8: Type `com.tencent.tinker.lib.util.UpgradePatchRetry` was not found, it is required for default or static interface methods desugaring of `void com.tencent.bugly.beta.tinker.TinkerLoadReporter.onLoadFileNotFound(java.io.File, int, boolean)`
/Users/leelion6/Documents/work space/AgentBear/app/build/intermediates/transforms/appJoint/debug/120.jar: D8: Type `com.tencent.tinker.loader.shareutil.SharePatchFileUtil` was not found, it is required for default or static interface methods desugaring of `void com.tencent.bugly.beta.tinker.TinkerLoadReporter.onLoadFileNotFound(java.io.File, int, boolean)`
/Users/leelion6/Documents/work space/AgentBear/app/build/intermediates/transforms/appJoint/debug/120.jar: D8: Type `com.tencent.tinker.lib.tinker.TinkerInstaller` was not found, it is required for default or static interface methods desugaring of `void com.tencent.bugly.beta.tinker.TinkerLoadReporter.onLoadFileNotFound(java.io.File, int, boolean)`
D8: Type com.tencent.bugly.proguard.ar is referenced as an interface from `com.tencent.bugly.proguard.at`.
/Users/leelion6/Documents/work space/AgentBear/app/build/intermediates/transforms/appJoint/debug/120.jar: D8: Type `com.tencent.tinker.lib.util.TinkerLog` was not found, it is required for default or static interface methods desugaring of `void com.tencent.bugly.beta.tinker.TinkerUtils$ScreenState$1.onReceive(android.content.Context, android.content.Intent)`
/Users/leelion6/Documents/work space/AgentBear/app/build/intermediates/transforms/appJoint/debug/120.jar: D8: Type `com.tencent.tinker.lib.tinker.Tinker` was not found, it is required for default or static interface methods desugaring of `void com.tencent.bugly.beta.tinker.TinkerUtils.rollbackPatch(android.content.Context)`

> Task :app:transformClassesWithDexBuilderForDebug 
com.android.builder.dexing.DexArchiveBuilderException: com.android.builder.dexing.DexArchiveBuilderException: Failed to process /Users/leelion6/Documents/work space/AgentBear/app/build/intermediates/transforms/appJoint/debug/120.jar
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:593)
        at java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:677)
        at java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:720)
        at com.android.ide.common.internal.WaitableExecutor.waitForTasksWithQuickFail(WaitableExecutor.java:146)
        at com.android.build.gradle.internal.transforms.DexArchiveBuilderTransform.transform(DexArchiveBuilderTransform.java:405)
        at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:239)
        at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:235)
        at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:102)
        at com.android.build.gradle.internal.pipeline.TransformTask.transform(TransformTask.java:230)
        at sun.reflect.GeneratedMethodAccessor546.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.IncrementalTaskAction.doExecute(IncrementalTaskAction.java:50)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:124)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:113)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:95)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:73)
        at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
        at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:256)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:249)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:238)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:123)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:79)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:104)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:98)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:663)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:597)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:98)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
        at java.lang.Thread.run(Thread.java:748)
Caused by: com.android.builder.dexing.DexArchiveBuilderException: Failed to process /Users/leelion6/Documents/work space/AgentBear/app/build/intermediates/transforms/appJoint/debug/120.jar
        at com.android.build.gradle.internal.transforms.DexArchiveBuilderTransform.launchProcessing(DexArchiveBuilderTransform.java:900)
        at com.android.build.gradle.internal.transforms.DexArchiveBuilderTransform.lambda$convertToDexArchive$6(DexArchiveBuilderTransform.java:825)
        at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1424)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: com.android.builder.dexing.DexArchiveBuilderException: Error while dexing.
        at com.android.builder.dexing.D8DexArchiveBuilder.getExceptionToRethrow(D8DexArchiveBuilder.java:124)
        at com.android.builder.dexing.D8DexArchiveBuilder.convert(D8DexArchiveBuilder.java:101)
        at com.android.build.gradle.internal.transforms.DexArchiveBuilderTransform.launchProcessing(DexArchiveBuilderTransform.java:895)
        ... 6 more
Caused by: com.android.tools.r8.CompilationFailedException: Compilation failed to complete
        at com.android.tools.r8.utils.ExceptionUtils.withCompilationHandler(ExceptionUtils.java:65)
        at com.android.tools.r8.utils.ExceptionUtils.withD8CompilationHandler(ExceptionUtils.java:43)
        at com.android.tools.r8.D8.run(D8.java:90)
        at com.android.builder.dexing.D8DexArchiveBuilder.convert(D8DexArchiveBuilder.java:99)
        ... 7 more
Caused by: com.android.tools.r8.utils.AbortException: Error: Type com.tencent.bugly.proguard.ar is referenced as an interface from `com.tencent.bugly.proguard.at`.
        at com.android.tools.r8.utils.Reporter.failIfPendingErrors(Reporter.java:116)
        at com.android.tools.r8.utils.Reporter.fatalError(Reporter.java:74)
        at com.android.tools.r8.utils.ExceptionUtils.withCompilationHandler(ExceptionUtils.java:59)
        ... 10 more

/Users/leelion6/Documents/work space/AgentBear/app/build/intermediates/transforms/appJoint/debug/120.jar: D8: Type `com.tencent.tinker.loader.app.TinkerApplication` was not found, it is required for default or static interface methods desugaring of `void com.tencent.bugly.beta.tinker.TinkerPatchReflectApplication.attachBaseContext(android.content.Context)`
/Users/leelion6/Documents/work space/AgentBear/app/build/intermediates/transforms/appJoint/debug/120.jar: D8: Type `com.tencent.tinker.loader.shareutil.ShareReflectUtil` was not found, it is required for default or static interface methods desugaring of `void com.tencent.bugly.beta.tinker.TinkerPatchReflectApplication.onCreate()`
/Users/leelion6/Documents/work space/AgentBear/app/build/intermediates/transforms/appJoint/debug/120.jar: D8: Type `com.tencent.tinker.lib.library.TinkerLoadLibrary` was not found, it is required for default or static interface methods desugaring of `void com.tencent.bugly.beta.tinker.TinkerManager.loadArmLibrary(android.content.Context, java.lang.String)`
/Users/leelion6/Documents/work space/AgentBear/app/build/intermediates/transforms/appJoint/debug/120.jar: D8: Type `com.tencent.tinker.lib.tinker.TinkerApplicationHelper` was not found, it is required for default or static interface methods desugaring of `java.lang.String com.tencent.bugly.beta.tinker.TinkerManager.getTinkerId()`
/Users/leelion6/Documents/work space/AgentBear/app/build/intermediates/transforms/appJoint/debug/120.jar: D8: Type `com.tencent.tinker.loader.shareutil.ShareTinkerInternals` was not found, it is required for default or static interface methods desugaring of `java.lang.String com.tencent.bugly.beta.tinker.TinkerManager.getTinkerId()`

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesWithDexBuilderForDebug'.
> com.android.build.api.transform.TransformException: com.android.builder.dexing.DexArchiveBuilderException: com.android.builder.dexing.DexArchiveBuilderException: Failed to process /Users/leelion6/Documents/work space/AgentBear/app/build/intermediates/transforms/appJoint/debug/120.jar

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:transformClassesWithDexBuilderForDebug'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:103)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:73)
        at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
        at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:256)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:249)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:238)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:123)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:79)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:104)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:98)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:663)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:597)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:98)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: java.lang.RuntimeException: com.android.build.api.transform.TransformException: com.android.builder.dexing.DexArchiveBuilderException: com.android.builder.dexing.DexArchiveBuilderException: Failed to process /Users/leelion6/Documents/work space/AgentBear/app/build/intermediates/transforms/appJoint/debug/120.jar
        at com.android.builder.profile.Recorder$Block.handleException(Recorder.java:55)
        at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:104)
        at com.android.build.gradle.internal.pipeline.TransformTask.transform(TransformTask.java:230)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.IncrementalTaskAction.doExecute(IncrementalTaskAction.java:50)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:124)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:113)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:95)
        ... 30 more
Caused by: com.android.build.api.transform.TransformException: com.android.builder.dexing.DexArchiveBuilderException: com.android.builder.dexing.DexArchiveBuilderException: Failed to process /Users/leelion6/Documents/work space/AgentBear/app/build/intermediates/transforms/appJoint/debug/120.jar
        at com.android.build.gradle.internal.transforms.DexArchiveBuilderTransform.transform(DexArchiveBuilderTransform.java:427)
        at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:239)
        at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:235)
        at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:102)
        ... 42 more
Caused by: com.android.builder.dexing.DexArchiveBuilderException: com.android.builder.dexing.DexArchiveBuilderException: Failed to process /Users/leelion6/Documents/work space/AgentBear/app/build/intermediates/transforms/appJoint/debug/120.jar
        at com.android.ide.common.internal.WaitableExecutor.waitForTasksWithQuickFail(WaitableExecutor.java:146)
        at com.android.build.gradle.internal.transforms.DexArchiveBuilderTransform.transform(DexArchiveBuilderTransform.java:405)
        ... 45 more
Caused by: com.android.builder.dexing.DexArchiveBuilderException: Failed to process /Users/leelion6/Documents/work space/AgentBear/app/build/intermediates/transforms/appJoint/debug/120.jar
        at com.android.build.gradle.internal.transforms.DexArchiveBuilderTransform.launchProcessing(DexArchiveBuilderTransform.java:900)
        at com.android.build.gradle.internal.transforms.DexArchiveBuilderTransform.lambda$convertToDexArchive$6(DexArchiveBuilderTransform.java:825)
Caused by: com.android.builder.dexing.DexArchiveBuilderException: Error while dexing.
        at com.android.builder.dexing.D8DexArchiveBuilder.getExceptionToRethrow(D8DexArchiveBuilder.java:124)
        at com.android.builder.dexing.D8DexArchiveBuilder.convert(D8DexArchiveBuilder.java:101)
        at com.android.build.gradle.internal.transforms.DexArchiveBuilderTransform.launchProcessing(DexArchiveBuilderTransform.java:895)
        ... 1 more
Caused by: com.android.tools.r8.CompilationFailedException: Compilation failed to complete
        at com.android.tools.r8.utils.ExceptionUtils.withCompilationHandler(ExceptionUtils.java:65)
        at com.android.tools.r8.utils.ExceptionUtils.withD8CompilationHandler(ExceptionUtils.java:43)
        at com.android.tools.r8.D8.run(D8.java:90)
        at com.android.builder.dexing.D8DexArchiveBuilder.convert(D8DexArchiveBuilder.java:99)
        ... 2 more
Caused by: com.android.tools.r8.utils.AbortException: Error: Type com.tencent.bugly.proguard.ar is referenced as an interface from `com.tencent.bugly.proguard.at`.
        at com.android.tools.r8.utils.Reporter.failIfPendingErrors(Reporter.java:116)
        at com.android.tools.r8.utils.Reporter.fatalError(Reporter.java:74)
        at com.android.tools.r8.utils.ExceptionUtils.withCompilationHandler(ExceptionUtils.java:59)
        ... 5 more

* Get more help at https://help.gradle.org

**Comment by Leelion96** [comment]
已解决 原来是项目依赖的其中有一个库 也依赖了bugly 而upgrade和普通版的bugly是不能共存的  没有提示  一个一个排除出来  很头痛
