### ISSUE TITLE
热修复在小米手机合成异常

### ISSUE THREAD

**Issue by zsj6102** [BuglyDevTeam/Bugly-Android-Demo#168]
#### 异常类型
  app运行时异常 

#### 手机型号
 小米 REDMI 6A 

#### 手机系统版本
Android 8.1.0,level 27

#### Tinker版本
 1.9.9

#### gradle版本
gradle-5.1.1-all

#### 系统
Win7

#### 堆栈/日志
2019-08-09 17:48:11.642 9077-9091/com.zsj.app E/StrictMode: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
    java.lang.Throwable: Explicit termination method 'close' not called
        at dalvik.system.CloseGuard.open(CloseGuard.java:223)
        at java.util.zip.ZipFile.<init>(ZipFile.java:250)
        at java.util.zip.ZipFile.<init>(ZipFile.java:149)
        at java.util.jar.JarFile.<init>(JarFile.java:160)
        at java.util.jar.JarFile.<init>(JarFile.java:124)
        at com.tencent.bugly.beta.tinker.TinkerUtils.readJarEntry(BUGLY:302)
        at com.tencent.bugly.beta.tinker.TinkerManager.checkNewPatch(BUGLY:477)
        at com.tencent.bugly.beta.tinker.TinkerManager.applyPatch(BUGLY:431)
        at com.tencent.bugly.beta.tinker.TinkerManager.onDownloadSuccess(BUGLY:409)
        at com.tencent.bugly.beta.download.a.onCompleted(BUGLY:203)
        at com.tencent.bugly.beta.global.d.run(BUGLY:263)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:171)
        at android.app.ActivityThread.main(ActivityThread.java:6642)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:518)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

#### 复现路径
发布补丁，看log补丁是下载下来了，合成的时候抛出上面那个异常

**Comment by xyc1120** [comment]
我也有同样的问题，补丁下载下来了，合成时就异常了，请教下你解决了吗
