### ISSUE TITLE
java.io.FileNotFoundException: /system/build.prop (Permission denied)

### ISSUE THREAD

**Issue by tenvick** [BuglyDevTeam/Bugly-Android-Demo#178]
#### 异常类型

09-19 10:30:39.609 19671 19928 W System.err: java.io.FileNotFoundException: /system/build.prop (Permission denied)
09-19 10:30:39.610 19671 19928 W System.err: 	at java.io.FileInputStream.open0(Native Method)
09-19 10:30:39.610 19671 19928 W System.err: 	at java.io.FileInputStream.open(FileInputStream.java:231)
09-19 10:30:39.610 19671 19928 W System.err: 	at java.io.FileInputStream.<init>(FileInputStream.java:165)
09-19 10:30:39.610 19671 19928 W System.err: 	at java.io.FileInputStream.<init>(FileInputStream.java:112)
09-19 10:30:39.610 19671 19928 W System.err: 	at java.io.FileReader.<init>(FileReader.java:58)
09-19 10:30:39.610 19671 19928 W System.err: 	at com.tencent.bugly.crashreport.common.info.b.p(BUGLY:229)
09-19 10:30:39.610 19671 19928 W System.err: 	at com.tencent.bugly.crashreport.common.info.b.a(BUGLY:288)
09-19 10:30:39.610 19671 19928 W System.err: 	at com.tencent.bugly.crashreport.common.info.a.r(BUGLY:507)
09-19 10:30:39.610 19671 19928 W System.err: 	at com.tencent.bugly.proguard.a.a(BUGLY:160)
09-19 10:30:39.610 19671 19928 W System.err: 	at com.tencent.bugly.crashreport.biz.a.c(BUGLY:271)
09-19 10:30:39.610 19671 19928 W System.err: 	at com.tencent.bugly.crashreport.biz.a.a(BUGLY:35)
09-19 10:30:39.610 19671 19928 W System.err: 	at com.tencent.bugly.crashreport.biz.a$2.run(BUGLY:335)
09-19 10:30:39.610 19671 19928 W System.err: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
09-19 10:30:39.610 19671 19928 W System.err: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
09-19 10:30:39.610 19671 19928 W System.err: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
09-19 10:30:39.610 19671 19928 W System.err: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
09-19 10:30:39.610 19671 19928 W System.err: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
09-19 10:30:39.610 19671 19928 W System.err: 	at java.lang.Thread.run(Thread.java:764)
#### 手机系统版本

小米 REDMI NOTE 5
系统版本Android 9,level 28
CPU架构armeabi

**Comment by zhhp1121** [comment]
> #### 异常类型
> 09-19 10:30:39.609 19671 19928 W System.err: java.io.FileNotFoundException: /system/build.prop (Permission denied)
> 09-19 10:30:39.610 19671 19928 W System.err: at java.io.FileInputStream.open0(Native Method)
> 09-19 10:30:39.610 19671 19928 W System.err: at java.io.FileInputStream.open(FileInputStream.java:231)
> 09-19 10:30:39.610 19671 19928 W System.err: at java.io.FileInputStream.(FileInputStream.java:165)
> 09-19 10:30:39.610 19671 19928 W System.err: at java.io.FileInputStream.(FileInputStream.java:112)
> 09-19 10:30:39.610 19671 19928 W System.err: at java.io.FileReader.(FileReader.java:58)
> 09-19 10:30:39.610 19671 19928 W System.err: at com.tencent.bugly.crashreport.common.info.b.p(BUGLY:229)
> 09-19 10:30:39.610 19671 19928 W System.err: at com.tencent.bugly.crashreport.common.info.b.a(BUGLY:288)
> 09-19 10:30:39.610 19671 19928 W System.err: at com.tencent.bugly.crashreport.common.info.a.r(BUGLY:507)
> 09-19 10:30:39.610 19671 19928 W System.err: at com.tencent.bugly.proguard.a.a(BUGLY:160)
> 09-19 10:30:39.610 19671 19928 W System.err: at com.tencent.bugly.crashreport.biz.a.c(BUGLY:271)
> 09-19 10:30:39.610 19671 19928 W System.err: at com.tencent.bugly.crashreport.biz.a.a(BUGLY:35)
> 09-19 10:30:39.610 19671 19928 W System.err: at com.tencent.bugly.crashreport.biz.a$2.run(BUGLY:335)
> 09-19 10:30:39.610 19671 19928 W System.err: at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
> 09-19 10:30:39.610 19671 19928 W System.err: at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 09-19 10:30:39.610 19671 19928 W System.err: at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
> 09-19 10:30:39.610 19671 19928 W System.err: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
> 09-19 10:30:39.610 19671 19928 W System.err: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
> 09-19 10:30:39.610 19671 19928 W System.err: at java.lang.Thread.run(Thread.java:764)
> 
> #### 手机型号
> #### 手机系统版本
> 小米 REDMI NOTE 5
> 系统版本Android 9,level 28
> CPU架构armeabi
> 
> #### Tinker版本
> #### gradle版本
> #### 系统
> #### 堆栈/日志
> #### 复现路径

这个是被捕获的异常，对功能没有影响
