### ISSUE TITLE
点击 “立即更新” 报错

### ISSUE THREAD

**Issue by whnpneo** [BuglyDevTeam/Bugly-Android-Demo#186]
#### 异常类型
app运行时异常 

#### 手机型号
小米 REDMI 6 PRO

#### 手机系统版本 
Android 9,level 28

#### Tinker版本
tinker lib 1.9.14,tinker-support版本1.2.0

#### 堆栈/日志
10-16 21:08:38.082 W/System.err( 7453): java.lang.IllegalArgumentException: Invalid notification (no valid small icon): Notification(channel=001 pri=0 contentView=null vibrate=null sound=null tick defaults=0x0 flags=0x0 color=0x00000000 vis=PRIVATE)
10-16 21:08:38.082 W/System.err( 7453): 	at android.app.NotificationManager.notifyAsUser(NotificationManager.java:396)
10-16 21:08:38.082 W/System.err( 7453): 	at android.app.NotificationManager.notify(NotificationManager.java:373)
10-16 21:08:38.083 W/System.err( 7453): 	at android.app.NotificationManager.notify(NotificationManager.java:349)
10-16 21:08:38.083 W/System.err( 7453): 	at com.tencent.bugly.beta.ui.c.a(BUGLY:129)
10-16 21:08:38.083 W/System.err( 7453): 	at com.tencent.bugly.proguard.t.download(BUGLY:101)
10-16 21:08:38.083 W/System.err( 7453): 	at com.tencent.bugly.beta.global.b.onClick(BUGLY:91)
10-16 21:08:38.084 W/System.err( 7453): 	at android.view.View.performClick(View.java:6616)
10-16 21:08:38.084 W/System.err( 7453): 	at android.view.View.performClickInternal(View.java:6593)
10-16 21:08:38.084 W/System.err( 7453): 	at android.view.View.access$3100(View.java:785)
10-16 21:08:38.084 W/System.err( 7453): 	at android.view.View$PerformClick.run(View.java:25929)
10-16 21:08:38.085 W/System.err( 7453): 	at android.os.Handler.handleCallback(Handler.java:873)
10-16 21:08:38.085 W/System.err( 7453): 	at android.os.Handler.dispatchMessage(Handler.java:99)
10-16 21:08:38.085 W/System.err( 7453): 	at android.os.Looper.loop(Looper.java:201)
10-16 21:08:38.085 W/System.err( 7453): 	at android.app.ActivityThread.main(ActivityThread.java:6806)
10-16 21:08:38.086 W/System.err( 7453): 	at java.lang.reflect.Method.invoke(Native Method)
10-16 21:08:38.086 W/System.err( 7453): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
10-16 21:08:38.086 W/System.err( 7453): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

**Comment by jingliancui** [comment]
@whnpneo Please check it 

https://github.com/jingliancui/XamarinFormsTencentBuglySample

https://mp.weixin.qq.com/s/-B8UP4RSAiNPp68wYymz4A
