### ISSUE TITLE
9.0版本启动闪退就不去

### ISSUE THREAD

**Issue by yezi10086** [BuglyDevTeam/Bugly-Android-Demo#197]
#### 异常类型

 E/mple.tinkerdem: [qarth_debug:]  get PatchStore::createDisableExceptionQarthFile method fail.
2019-11-26 15:20:15.717 5277-5277/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.tinkerdemo, PID: 5277
    java.lang.RuntimeException: Unable to instantiate application com.example.tinkerdemo.SampleApplication: com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:createDelegate failed
        at android.app.LoadedApk.makeApplication(LoadedApk.java:1190)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6674)
        at android.app.ActivityThread.access$2000(ActivityThread.java:259)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2028)
        at android.os.Handler.dispatchMessage(Handler.java:112)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7586)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
     Caused by: com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:createDelegate failed
        at com.tencent.tinker.loader.app.TinkerApplication.createDelegate(Unknown Source:99)
        at com.tencent.tinker.loader.app.TinkerApplication.ensureDelegate(Unknown Source:5)
        at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(Unknown Source:15)
        at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(Unknown Source:11)
        at android.app.Application.attach(Application.java:224)
        at android.app.Instrumentation.newApplication(Instrumentation.java:1128)
        at android.app.LoadedApk.makeApplication(LoadedApk.java:1182)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6674) 
        at android.app.ActivityThread.access$2000(ActivityThread.java:259) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2028) 
        at android.os.Handler.dispatchMessage(Handler.java:112) 
        at android.os.Looper.loop(Looper.java:216) 
        at android.app.ActivityThread.main(ActivityThread.java:7586) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034) 
     Caused by: java.lang.ClassNotFoundException: com.example.tinkerdemo.SampleApplicationLike
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:453)
        at com.tencent.tinker.loader.app.TinkerApplication.createDelegate(Unknown Source:7)
        at com.tencent.tinker.loader.app.TinkerApplication.ensureDelegate(Unknown Source:5) 
        at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(Unknown Source:15) 
        at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(Unknown Source:11) 
        at android.app.Application.attach(Application.java:224) 
        at android.app.Instrumentation.newApplication(Instrumentation.java:1128) 
        at android.app.LoadedApk.makeApplication(LoadedApk.java:1182) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6674) 
        at android.app.ActivityThread.access$2000(ActivityThread.java:259) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2028) 
        at android.os.Handler.dispatchMessage(Handler.java:112) 
        at android.os.Looper.loop(Looper.java:216) 
        at android.app.ActivityThread.main(ActivityThread.java:7586) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034) 
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.example.tinkerdemo.SampleApplicationLike" on path: DexPathList[[zip file "/data/app/com.example.tinkerdemo-3_9HS_G-aYEDMG1Impf9fA==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.tinkerdemo-3_9HS_G-aYEDMG1Impf9fA==/lib/arm, /data/app/com.example.tinkerdemo-3_9HS_G-aYEDMG1Impf9fA==/base.apk!/lib/armeabi, /system/lib, /product/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at java.lang.Class.classForName(Native Method) 
        at java.lang.Class.forName(Class.java:453) 
        at com.tencent.tinker.loader.app.TinkerApplication.createDelegate(Unknown Source:7) 
        at com.tencent.tinker.loader.app.TinkerApplication.ensureDelegate(Unknown Source:5) 
        at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(Unknown Source:15) 
        at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(Unknown Source:11) 
        at android.app.Application.attach(Application.java:224) 
        at android.app.Instrumentation.newApplication(Instrumentation.java:1128) 
        at android.app.LoadedApk.makeApplication(LoadedApk.java:1182) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6674) 
        at android.app.ActivityThread.access$2000(ActivityThread.java:259) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2028) 
        at android.os.Handler.dispatchMessage(Handler.java:112) 
        at android.os.Looper.loop(Looper.java:216) 
        at android.app.ActivityThread.main(ActivityThread.java:7586) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034) 
2019-11-26 15:20:15.719 5277-5277/? E/Tinker.UncaughtHandler: TinkerUncaughtHandler catch exception:java.lang.RuntimeException: Unable to instantiate application com.example.tinkerdemo.SampleApplication: com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:createDelegate failed
        at android.app.LoadedApk.makeApplication(LoadedApk.java:1190)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6674)
        at android.app.ActivityThread.access$2000(ActivityThread.java:259)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2028)
        at android.os.Handler.dispatchMessage(Handler.java:112)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7586)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
     Caused by: com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:createDelegate failed
        at com.tencent.tinker.loader.app.TinkerApplication.createDelegate(Unknown Source:99)
        at com.tencent.tinker.loader.app.TinkerApplication.ensureDelegate(Unknown Source:5)
        at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(Unknown Source:15)
        at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(Unknown Source:11)
        at android.app.Application.attach(Application.java:224)
        at android.app.Instrumentation.newApplication(Instrumentation.java:1128)
        at android.app.LoadedApk.makeApplication(LoadedApk.java:1182)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6674) 
        at android.app.ActivityThread.access$2000(ActivityThread.java:259) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2028) 
        at android.os.Handler.dispatchMessage(Handler.java:112) 
        at android.os.Looper.loop(Looper.java:216) 
        at android.app.ActivityThread.main(ActivityThread.java:7586) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034) 
     Caused by: java.lang.ClassNotFoundException: com.example.tinkerdemo.SampleApplicationLike
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:453)
        at com.tencent.tinker.loader.app.TinkerApplication.createDelegate(Unknown Source:7)
        at com.tencent.tinker.loader.app.TinkerApplication.ensureDelegate(Unknown Source:5) 
        at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(Unknown Source:15) 
        at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(Unknown Source:11) 
        at android.app.Application.attach(Application.java:224) 
        at android.app.Instrumentation.newApplication(Instrumentation.java:1128) 
        at android.app.LoadedApk.makeApplication(LoadedApk.java:1182) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6674) 
        at android.app.ActivityThread.access$2000(ActivityThread.java:259) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2028) 
        at android.os.Handler.dispatchMessage(Handler.java:112) 
        at android.os.Looper.loop(Looper.java:216) 
        at android.app.ActivityThread.main(ActivityThread.java:7586) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034) 
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.example.tinkerdemo.SampleApplicationLike" on path: DexPathList[[zip file "/data/app/com.example.tinkerdemo-3_9HS_G-aYEDMG1Impf9fA==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.tinkerdemo-3_9HS_G-aYEDMG1Impf9fA==/lib/arm, /data/app/com.example.tinkerdemo-3_9HS_G-aYEDMG1Impf9fA==/base.apk!/lib/armeabi, /system/lib, /product/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at java.lang.Class.classForName(Native Method) 
        at java.lang.Class.forName(Class.java:453) 
        at com.tencent.tinker.loader.app.TinkerApplication.createDelegate(Unknown Source:7) 
        at com.tencent.tinker.loader.app.TinkerApplication.ensureDelegate(Unknown Source:5) 
        at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(Unknown Source:15) 
        at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(Unknown Source:11) 
        at android.app.Application.attach(Application.java:224) 
        at android.app.Instrumentation.newApplication(Instrumentation.java:1128) 
        at android.app.LoadedApk.makeApplication(LoadedApk.java:1182) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6674) 
        at android.app.ActivityThread.access$2000(ActivityThread.java:259) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2028) 
        at android.os.Handler.dispatchMessage(Handler.java:112) 
        at android.os.Looper.loop(Looper.java:216) 
        at android.app.ActivityThread.main(ActivityThread.java:7586) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034) 

#### 手机型号

华为9x 

#### 手机系统版本

9.0

#### Tinker版本

1.9.6

#### gradle版本

5.4.1

**Comment by yezi10086** [comment]
生成的一个基准apk ,放进手机测试，在5.0版本的模拟器却可以打开

**Comment by Bobi-xiong** [comment]
我也遇到同样问题，混淆的问题，Application混淆忽略也一样报错

**Comment by Bobi-xiong** [comment]
使用“enableProxyApplication = true”方式配置Application就行了

**Comment by yezi10086** [comment]
> 使用“ enableProxyApplication = true”方式配置Application就行了

谢谢，我试试看看

**Comment by yezi10086** [comment]
> > 使用“ enableProxyApplication = true”方式配置Application就行了
> 
> 谢谢，我试试看看
enableProxyApplication = true,我试过了，但还是不行

**Comment by yezi10086** [comment]
> 使用“ enableProxyApplication = true”方式配置Application就行了

我这边一开始是用的的enableProxyApplication=false的配置来调试

**Comment by Bobi-xiong** [comment]
我也是，后台改为“ enableProxyApplication = true”配置就行了
implementation 'com.tencent.bugly:crashreport_upgrade:1.3.6'
    implementation 'com.tencent.bugly:nativecrashreport:3.3.1'
    implementation 'com.tencent.tinker:tinker-android-lib:1.9.9'这是我的依赖

**Comment by yezi10086** [comment]
2019-12-06 16:44:46.035 21519-21519/com.example.tinkerdemo E/Tinker.UncaughtHandler: TinkerUncaughtHandler catch exception:java.lang.RuntimeException: Unable to instantiate application com.example.tinkerdemo.SampleApplication: com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:createDelegate failed
        at android.app.LoadedApk.makeApplication(LoadedApk.java:855)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5629)
        at android.app.ActivityThread.-wrap2(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1637)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:156)
        at android.app.ActivityThread.main(ActivityThread.java:6517)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
     Caused by: com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:createDelegate failed
        at com.tencent.tinker.loader.app.TinkerApplication.createDelegate(:114)
        at com.tencent.tinker.loader.app.TinkerApplication.ensureDelegate(:120)
        at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(:133)
        at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(:148)
        at android.app.Application.attach(Application.java:189)
        at android.app.Instrumentation.newApplication(Instrumentation.java:1011)
        at android.app.Instrumentation.newApplication(Instrumentation.java:995)
        at android.app.LoadedApk.makeApplication(LoadedApk.java:849)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5629) 
        at android.app.ActivityThread.-wrap2(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1637) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:156) 
        at android.app.ActivityThread.main(ActivityThread.java:6517) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832) 
     Caused by: java.lang.ClassNotFoundException: com.example.tinkerdemo.SampleApplicationLike
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:400)
        at com.tencent.tinker.loader.app.TinkerApplication.createDelegate(:108)
        at com.tencent.tinker.loader.app.TinkerApplication.ensureDelegate(:120) 
        at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(:133) 
        at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(:148) 
        at android.app.Application.attach(Application.java:189) 
        at android.app.Instrumentation.newApplication(Instrumentation.java:1011) 
        at android.app.Instrumentation.newApplication(Instrumentation.java:995) 
        at android.app.LoadedApk.makeApplication(LoadedApk.java:849) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5629) 
        at android.app.ActivityThread.-wrap2(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1637) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:156) 
        at android.app.ActivityThread.main(ActivityThread.java:6517) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832) 
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.example.tinkerdemo.SampleApplicationLike" on path: DexPathList[[zip file "/data/app/com.example.tinkerdemo-1/base.apk"],nativeLibraryDirectories=[/data/app/com.example.tinkerdemo-1/lib/arm64, /data/app/com.example.tinkerdemo-1/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64, /system/vendor/lib64, /product/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at java.lang.Class.classForName(Native Method) 
        at java.lang.Class.forName(Class.java:400) 
        at com.tencent.tinker.loader.app.TinkerApplication.createDelegate(:108) 
        at com.tencent.tinker.loader.app.TinkerApplication.ensureDelegate(:120) 
        at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(:133) 
        at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(:148) 
        at android.app.Application.attach(Application.java:189) 
        at android.app.Instrumentation.newApplication(Instrumentation.java:1011) 
        at android.app.Instrumentation.newApplication(Instrumentation.java:995) 
        at android.app.LoadedApk.makeApplication(LoadedApk.java:849) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5629) 
        at android.app.ActivityThread.-wrap2(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1637) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:156) 
        at android.app.ActivityThread.main(ActivityThread.java:6517) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832) 
2019-12-06 16:44:46.035 21519-21519/com.example.tinkerdemo E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.tinkerdemo, PID: 21519
    java.lang.RuntimeException: Unable to instantiate application com.example.tinkerdemo.SampleApplication: com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:createDelegate failed
        at android.app.LoadedApk.makeApplication(LoadedApk.java:855)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5629)
        at android.app.ActivityThread.-wrap2(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1637)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:156)
        at android.app.ActivityThread.main(ActivityThread.java:6517)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
     Caused by: com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:createDelegate failed
        at com.tencent.tinker.loader.app.TinkerApplication.createDelegate(:114)
        at com.tencent.tinker.loader.app.TinkerApplication.ensureDelegate(:120)
        at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(:133)
        at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(:148)
        at android.app.Application.attach(Application.java:189)
        at android.app.Instrumentation.newApplication(Instrumentation.java:1011)
        at android.app.Instrumentation.newApplication(Instrumentation.java:995)
        at android.app.LoadedApk.makeApplication(LoadedApk.java:849)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5629) 
        at android.app.ActivityThread.-wrap2(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1637) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:156) 
        at android.app.ActivityThread.main(ActivityThread.java:6517) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832) 
     Caused by: java.lang.ClassNotFoundException: com.example.tinkerdemo.SampleApplicationLike
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:400)
        at com.tencent.tinker.loader.app.TinkerApplication.createDelegate(:108)
        at com.tencent.tinker.loader.app.TinkerApplication.ensureDelegate(:120) 
        at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(:133) 
        at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(:148) 
        at android.app.Application.attach(Application.java:189) 
        at android.app.Instrumentation.newApplication(Instrumentation.java:1011) 
        at android.app.Instrumentation.newApplication(Instrumentation.java:995) 
        at android.app.LoadedApk.makeApplication(LoadedApk.java:849) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5629) 
        at android.app.ActivityThread.-wrap2(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1637) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:156) 
        at android.app.ActivityThread.main(ActivityThread.java:6517) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832) 
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.example.tinkerdemo.SampleApplicationLike" on path: DexPathList[[zip file "/data/app/com.example.tinkerdemo-1/base.apk"],nativeLibraryDirectories=[/data/app/com.example.tinkerdemo-1/lib/arm64, /data/app/com.example.tinkerdemo-1/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64, /system/vendor/lib64, /product/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at java.lang.Class.classForName(Native Method) 
        at java.lang.Class.forName(Class.java:400) 
        at com.tencent.tinker.loader.app.TinkerApplication.createDelegate(:108) 
        at com.tencent.tinker.loader.app.TinkerApplication.ensureDelegate(:120) 
        at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(:133) 
        at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(:148) 
        at android.app.Application.attach(Application.java:189) 
        at android.app.Instrumentation.newApplication(Instrumentation.java:1011) 
        at android.app.Instrumentation.newApplication(Instrumentation.java:995) 
        at android.app.LoadedApk.makeApplication(LoadedApk.java:849) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5629) 
        at android.app.ActivityThread.-wrap2(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1637) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:156) 
        at android.app.ActivityThread.main(ActivityThread.java:6517) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832) 
2019-12-06 16:44:46.046 21519-21519/? I/Process: Sending signal. PID: 21519 SIG: 9
