### ISSUE TITLE
9.0的设备，enableProxyApplication设置为true，编译后的app崩溃，无法找到自定义的Application

### ISSUE THREAD

**Issue by Rulemylife** [BuglyDevTeam/Bugly-Android-Demo#208]
java.lang.RuntimeException: Unable to instantiate application com.tencent.bugly.beta.tinker.TinkerPatchReflectApplication: java.lang.IllegalStateException: java.lang.ClassNotFoundException: com.hang.buglytest.MySampleApplication
        at android.app.LoadedApk.makeApplication(LoadedApk.java:1095)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6174)
        at android.app.ActivityThread.access$1300(ActivityThread.java:208)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1795)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:7029)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

但是我自定义的Application明明有在Manifest文件中声明

**Comment by dapanjimianpaigumian** [comment]
我也遇到这个问题了，楼主解决了么？

**Comment by Like151320** [comment]
遇到相同的问题，同求解法

**Comment by wanghulin1998** [comment]
> 我也遇到这个问题了，楼主解决了么？

降低gradle版本

**Comment by Like151320** [comment]
我的解决了，如下
https://blog.csdn.net/qq_34224268/article/details/104779203

**Comment by liangdong9676** [comment]
官方说得好清楚了。。是不能用自己的Application了。
enableProxyApplication=为true就是无需改造Application，但官方不再维护，bugly只能用到 1.4.5 + 3.7.500 + 1.9.14.7版本。

1.9.14.8和以后的版本，需集成SampleApplicationLike。

目前最新是
api 'com.tencent.bugly:crashreport_upgrade:1.5.0'
api 'com.tencent.bugly:nativecrashreport:3.7.700'
api 'com.tencent.tinker:tinker-android-lib:1.9.14.10'
