### ISSUE TITLE
OPPO 手机崩溃：NoSuchMethodError: No direct method <init>(ILjava/lang/String;Ljava/lang/String;Z)V in class Lcom/tencent/tinker/loader/app/TinkerApplication

### ISSUE THREAD

**Issue by IvyLi** [BuglyDevTeam/Bugly-Android-Demo#269]
#### 异常类型
运行崩溃

#### 手机型号
OPPO R9s 

#### 手机系统版本
6.0.1

#### Tinker版本
1.9.14.7

#### gradle版本
5.6.4

#### 堆栈/日志
FATAL EXCEPTION: main Process:xxx, PID: 20447 
java.lang.NoSuchMethodError: No direct method <init>(ILjava/lang/String;Ljava/lang/String;Z)V in class Lcom/tencent/tinker/loader/app/TinkerApplication; or its super classes (declaration of 'com.tencent.tinker.loader.app.TinkerApplication' appears in /data/app/xxx.xxx.xxx-2/base.apk) 
at com.tencent.bugly.beta.tinker.TinkerPatchReflectApplication.<init>(BUGLY:44) 
at java.lang.Class.newInstance(Native Method) at android.app.Instrumentation.newApplication(Instrumentation.java:997) 
at android.app.Instrumentation.newApplication(Instrumentation.java:982) 
at android.app.LoadedApk.makeApplication(LoadedApk.java:614) 
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4968) 
at android.app.ActivityThread.access$1800(ActivityThread.java:170) 
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1555) 
at android.os.Handler.dispatchMessage(Handler.java:102) at android.os.Looper.loop(Looper.java:179) 
at android.app.ActivityThread.main(ActivityThread.java:5769) at java.lang.reflect.Method.invoke(Native Method) 
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:674)

#### 复现路径
OPPO R9s 必现，其他机器未发现

**Comment by liangdong9676** [comment]
官方说得好清楚了。。是不能用自己的Application了。
enableProxyApplication=为true就是无需改造Application，但官方不再维护，bugly只能用到 1.4.5 + 3.7.500 + 1.9.14.7版本。

1.9.14.8和以后的版本，需集成SampleApplicationLike。

目前最新是
api 'com.tencent.bugly:crashreport_upgrade:1.5.0'
api 'com.tencent.bugly:nativecrashreport:3.7.700'
api 'com.tencent.tinker:tinker-android-lib:1.9.14.10'
