### ISSUE TITLE
ExceptionInInitializerError

### ISSUE THREAD

**Issue by BugRui** [BuglyDevTeam/Bugly-Android-Demo#272]
2020-11-17 18:28:16.833 14459-14812/com.syc.slms W/System.err: java.lang.ExceptionInInitializerError
2020-11-17 18:28:16.833 14459-14812/com.syc.slms W/System.err:     at com.tencent.bugly.beta.upgrade.c.a(BUGLY:427)
2020-11-17 18:28:16.833 14459-14812/com.syc.slms W/System.err:     at com.tencent.bugly.beta.upgrade.c.a(BUGLY:302)
2020-11-17 18:28:16.833 14459-14812/com.syc.slms W/System.err:     at com.tencent.bugly.beta.upgrade.a.a(BUGLY:97)
2020-11-17 18:28:16.833 14459-14812/com.syc.slms W/System.err:     at com.tencent.bugly.proguard.al.a(BUGLY:188)
2020-11-17 18:28:16.833 14459-14812/com.syc.slms W/System.err:     at com.tencent.bugly.proguard.al.run(BUGLY:473)
2020-11-17 18:28:16.833 14459-14812/com.syc.slms W/System.err:     at com.tencent.bugly.proguard.ak$2.run(BUGLY:757)
2020-11-17 18:28:16.833 14459-14812/com.syc.slms W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
2020-11-17 18:28:16.833 14459-14812/com.syc.slms W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2020-11-17 18:28:16.833 14459-14812/com.syc.slms W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
2020-11-17 18:28:16.833 14459-14812/com.syc.slms W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2020-11-17 18:28:16.833 14459-14812/com.syc.slms W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2020-11-17 18:28:16.833 14459-14812/com.syc.slms W/System.err:     at java.lang.Thread.run(Thread.java:919)
2020-11-17 18:28:16.834 14459-14812/com.syc.slms W/System.err: Caused by: java.lang.IllegalStateException: Method addObserver must be called on the main thread
2020-11-17 18:28:16.834 14459-14812/com.syc.slms W/System.err:     at androidx.lifecycle.LifecycleRegistry.enforceMainThreadIfNeeded(LifecycleRegistry.java:317)
2020-11-17 18:28:16.834 14459-14812/com.syc.slms W/System.err:     at androidx.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.java:172)
2020-11-17 18:28:16.834 14459-14812/com.syc.slms W/System.err:     at androidx.fragment.app.Fragment.initLifecycle(Fragment.java:496)
2020-11-17 18:28:16.834 14459-14812/com.syc.slms W/System.err:     at androidx.fragment.app.Fragment.<init>(Fragment.java:476)
2020-11-17 18:28:16.834 14459-14812/com.syc.slms W/System.err:     at com.tencent.bugly.beta.ui.b.<init>(BUGLY:17)
2020-11-17 18:28:16.834 14459-14812/com.syc.slms W/System.err:     at com.tencent.bugly.beta.ui.a.<init>(BUGLY:44)
2020-11-17 18:28:16.834 14459-14812/com.syc.slms W/System.err:     at com.tencent.bugly.beta.ui.h.<init>(BUGLY:45)
2020-11-17 18:28:16.834 14459-14812/com.syc.slms W/System.err:     at com.tencent.bugly.beta.ui.h.<clinit>(BUGLY:60)
2020-11-17 18:28:16.834 14459-14812/com.syc.slms W/System.err: 	... 12 more

**Comment by BugRui** [comment]
和androidx.lifecycle:lifecycle-runtime-ktx库冲突了，我去掉这个库就可以，能解决一下吗？
