### ISSUE TITLE
补丁包更新后报java.lang.ClassNotFoundException: com.tencent.bugly.beta.ui.b

### ISSUE THREAD

**Issue by zqiang0898** [BuglyDevTeam/Bugly-Android-Demo#279]
#### 异常类型
java.lang.ClassNotFoundException: com.tencent.bugly.beta.ui.b

#### Tinker版本
classpath "com.tencent.bugly:tinker-support:1.2.0"

implementation 'com.tencent.bugly:crashreport_upgrade:1.4.1'
implementation 'com.tencent.tinker:tinker-android-lib:1.9.14.7'
implementation 'com.tencent.bugly:nativecrashreport:3.7.500'
#### gradle版本
gradle:3.5.2

#### 系统
window

#### 堆栈/日志
2020-12-01 17:44:52.015 22077-22077/com.tencent.bugly.hotfix E/CrashReport: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/tencent/bugly/beta/ui/b;
        at com.tencent.bugly.beta.Beta.installTinker(Unknown Source:0)
        at com.tencent.bugly.hotfix.SampleApplicationLike.onBaseContextAttached(SampleApplicationLike.java:110)
        at com.tencent.tinker.entry.TinkerApplicationInlineFence.handleMessageImpl(TinkerApplicationInlineFence.java:66)
        at com.tencent.tinker.entry.TinkerApplicationInlineFence.handleMessage_$noinline$(TinkerApplicationInlineFence.java:59)
        at com.tencent.tinker.entry.TinkerApplicationInlineFence.handleMessage(TinkerApplicationInlineFence.java:52)
        at com.tencent.tinker.loader.app.TinkerInlineFenceAction.callOnBaseContextAttached(TinkerInlineFenceAction.java:44)
        at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(TinkerApplication.java:141)
        at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(TinkerApplication.java:157)
        at android.app.Application.attach(Application.java:358)
        at android.app.Instrumentation.newApplication(Instrumentation.java:1168)
        at android.app.LoadedApk.makeApplication(LoadedApk.java:1296)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7320)
        at android.app.ActivityThread.access$2400(ActivityThread.java:308)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2295)
        at android.os.Handler.dispatchMessage(Handler.java:110)
        at android.os.Looper.loop(Looper.java:219)
        at android.app.ActivityThread.main(ActivityThread.java:8347)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)
     Caused by: java.lang.ClassNotFoundException: com.tencent.bugly.beta.ui.b
        at java.lang.VMClassLoader.findLoadedClass(Native Method)
        at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.tencent.bugly.beta.Beta.installTinker(Unknown Source:0) 
        at com.tencent.bugly.hotfix.SampleApplicationLike.onBaseContextAttached(SampleApplicationLike.java:110) 
        at com.tencent.tinker.entry.TinkerApplicationInlineFence.handleMessageImpl(TinkerApplicationInlineFence.java:66) 
        at com.tencent.tinker.entry.TinkerApplicationInlineFence.handleMessage_$noinline$(TinkerApplicationInlineFence.java:59) 
        at com.tencent.tinker.entry.TinkerApplicationInlineFence.handleMessage(TinkerApplicationInlineFence.java:52) 
        at com.tencent.tinker.loader.app.TinkerInlineFenceAction.callOnBaseContextAttached(TinkerInlineFenceAction.java:44) 
        at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(TinkerApplication.java:141) 
        at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(TinkerApplication.java:157) 
        at android.app.Application.attach(Application.java:358) 
        at android.app.Instrumentation.newApplication(Instrumentation.java:1168) 
        at android.app.LoadedApk.makeApplication(LoadedApk.java:1296) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7320) 
        at android.app.ActivityThread.access$2400(ActivityThread.java:308) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2295) 
        at android.os.Handler.dispatchMessage(Handler.java:110) 
        at android.os.Looper.loop(Looper.java:219) 
        at android.app.ActivityThread.main(ActivityThread.java:8347) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055) 
     Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/app/Fragment;
        at com.tencent.bugly.beta.Beta.installTinker(Unknown Source:0) 
        at com.tencent.bugly.hotfix.SampleApplicationLike.onBaseContextAttached(SampleApplicationLike.java:110) 
        at com.tencent.tinker.entry.TinkerApplicationInlineFence.handleMessageImpl(TinkerApplicationInlineFence.java:66) 
        at com.tencent.tinker.entry.TinkerApplicationInlineFence.handleMessage_$noinline$(TinkerApplicationInlineFence.java:59) 
        at com.tencent.tinker.entry.TinkerApplicationInlineFence.handleMessage(TinkerApplicationInlineFence.java:52) 
        at com.tencent.tinker.loader.app.TinkerInlineFenceAction.callOnBaseContextAttached(TinkerInlineFenceAction.java:44) 
        at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(TinkerApplication.java:141) 
        at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(TinkerApplication.java:157) 
        at android.app.Application.attach(Application.java:358) 
        at android.app.Instrumentation.newApplication(Instrumentation.java:1168) 
        at android.app.LoadedApk.makeApplication(LoadedApk.java:1296) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7320) 
        at android.app.ActivityThread.access$2400(ActivityThread.java:308) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2295) 
        at android.os.Handler.dispatchMessage(Handler.java:110) 
        at android.os.Looper.loop(Looper.java:219) 
        at android.app.ActivityThread.main(ActivityThread.java:8347) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055) 
     Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.app.Fragment" on path: DexPathList[[zip file "/data/app/com.tencent.bugly.hotfix-XMcgzVR_EWIbwiPnu-wdDw==/base.apk"],nativeLibraryDirectories=[/data/app/com.tencent.bugly.hotfix-XMcgzVR_EWIbwiPnu-wdDw==/lib/arm64, /data/app/com.tencent.bugly.hotfix-XMcgzVR_EWIbwiPnu-wdDw==/base.apk!/lib/arm64-v8a, /system/lib64, /hw_product/lib64, /system/product/lib64, /prets/lib64]]

#### 复现路径
com.tencent.bugly.beta.ui.b

**Comment by Jesse505** [comment]
这个我也遇到了，解决了吗

**Comment by skyofsky** [comment]
同样的问题,怎么解决的？3-15 16:15:17.400 3985-3985/com.tencent.bugly.hotfix E/Tinker.UncaughtHandler: TinkerUncaughtHandler catch exception:java.lang.NoClassDefFoundError: com.tencent.bugly.beta.ui.i
        at com.tencent.bugly.proguard.s.onApplySuccess(BUGLY:7)
        at com.tencent.bugly.beta.tinker.TinkerManager.onApplySuccess(BUGLY:2)
        at com.tencent.bugly.beta.tinker.TinkerResultService$1.run(BUGLY:2)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5307)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
    
    
    --------- beginning of crash
03-15 16:15:17.400 3985-3985/com.tencent.bugly.hotfix E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.tencent.bugly.hotfix, PID: 3985
    java.lang.NoClassDefFoundError: com.tencent.bugly.beta.ui.i
        at com.tencent.bugly.proguard.s.onApplySuccess(BUGLY:7)
        at com.tencent.bugly.beta.tinker.TinkerManager.onApplySuccess(BUGLY:2)
        at com.tencent.bugly.beta.tinker.TinkerResultService$1.run(BUGLY:2)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5307)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by eminfan** [comment]
> 这个我也遇到了，解决了吗

+1

**Comment by biaoShow** [comment]
![image](https://user-images.githubusercontent.com/37930146/124873168-b49cf200-dff8-11eb-9082-f91d7becf287.png)
我也遇到了，求解决方案

**Comment by biaoShow** [comment]
![image](https://user-images.githubusercontent.com/37930146/125044578-ac16eb00-e0ce-11eb-87e3-56dce302c69f.png)
我把canNotifyUserRestart这个关掉就不会报这个错误了
