### ISSUE TITLE
安装基准包报错

### ISSUE THREAD

**Issue by weball0310** [BuglyDevTeam/Bugly-Android-Demo#282]
2020-12-08 11:22:58.203 17855-17855/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.bianlimt.pltmu, PID: 17855
    java.lang.RuntimeException: Unable to instantiate application com.tencent.bugly.beta.tinker.TinkerPatchReflectApplication: java.lang.IllegalStateException: java.lang.ClassNotFoundException: com.bianlimt.pltmu.application.MainApplication
        at android.app.LoadedApk.makeApplication(LoadedApk.java:1183)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6688)

打包好基准包安装报错

**Comment by dcbinn** [comment]
添加混淆就好了
