### ISSUE TITLE
java.lang.RuntimeException: Unable to find binding constructor for com.countdown.niceday.activity.MainActivity

### ISSUE THREAD

**Issue by tianDuan** [BuglyDevTeam/Bugly-Android-Demo#295]
#### 异常类型

: TinkerUncaughtHandler catch exception:java.lang.RuntimeException: Unable to start activity ComponentInfo{com.countdown.niceday/com.countdown.niceday.activity.MainActivity}: java.lang.RuntimeException: Unable to find binding constructor for com.countdown.niceday.activity.MainActivity
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3403)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3587)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:86)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2185)
        at android.os.Handler.dispatchMessage(Handler.java:112)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7593)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
     Caused by: java.lang.RuntimeException: Unable to find binding constructor for com.countdown.niceday.activity.MainActivity
        at butterknife.ButterKnife.a(Unknown Source:122)
        at butterknife.ButterKnife.a(Unknown Source:34)
        at butterknife.ButterKnife.a(Unknown Source:8)
        at com.countdown.niceday.activity.MainActivity.onCreate(Unknown Source:9)
        at android.app.Activity.performCreate(Activity.java:7458)
        at android.app.Activity.performCreate(Activity.java:7448)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1286)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3382)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3587) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:86) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2185) 
        at android.os.Handler.dispatchMessage(Handler.java:112) 
        at android.os.Looper.loop(Looper.java:216) 
        at android.app.ActivityThread.main(ActivityThread.java:7593) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987) 
     Caused by: java.lang.NoSuchMethodException: <init> [class com.countdown.niceday.activity.MainActivity, class android.view.View]
        at java.lang.Class.getConstructor0(Class.java:2327)
        at java.lang.Class.getConstructor(Class.java:1725)
        at butterknife.ButterKnife.a(Unknown Source:86)

#### Tinker版本

support_version = "1.1.5"
tinker_version = "1.9.14.10"

#### gradle版本

gradle:3.3.3

**Comment by tianDuan** [comment]
@rocky666666
