### ISSUE TITLE
和androidx.lifecycle库冲突了

### ISSUE THREAD

**Issue by l12ab** [BuglyDevTeam/Bugly-Android-Demo#308]
#### 异常类型

W/CrashReport: java.lang.ExceptionInInitializerError
        at com.tencent.bugly.beta.upgrade.c.a(BUGLY:153)
        at com.tencent.bugly.beta.upgrade.c.a(BUGLY:117)
        at com.tencent.bugly.beta.upgrade.a.a(BUGLY:35)
        at com.tencent.bugly.proguard.U.a(BUGLY:16)
        at com.tencent.bugly.proguard.U.run(BUGLY:80)
        at com.tencent.bugly.proguard.S.run(BUGLY:3)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: java.lang.IllegalStateException: Method addObserver must be called on the main thread
        at androidx.lifecycle.LifecycleRegistry.enforceMainThreadIfNeeded(LifecycleRegistry.java:317)
        at androidx.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.java:172)
        at androidx.fragment.app.Fragment.initLifecycle(Fragment.java:471)
        at androidx.fragment.app.Fragment.<init>(Fragment.java:451)
        at com.tencent.bugly.beta.ui.e.<init>(BUGLY:1)
        at com.tencent.bugly.beta.ui.d.<init>(BUGLY:1)
        at com.tencent.bugly.beta.ui.l.<init>(BUGLY:1)
        at com.tencent.bugly.beta.ui.l.<clinit>(BUGLY:1)
        at com.tencent.bugly.beta.upgrade.c.a(BUGLY:153) 
        at com.tencent.bugly.beta.upgrade.c.a(BUGLY:117) 
        at com.tencent.bugly.beta.upgrade.a.a(BUGLY:35) 
        at com.tencent.bugly.proguard.U.a(BUGLY:16) 
        at com.tencent.bugly.proguard.U.run(BUGLY:80) 
        at com.tencent.bugly.proguard.S.run(BUGLY:3) 
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:919) 

#### 复现路径

出现上述错误时，无法弹出新版本的提示框
经过反复一个个测试验证，发现我的build.gradle里引用的如下三个库会导致上述的错误出现。

```
def lifecycle_version = "2.3.0"
implementation "androidx.lifecycle:lifecycle-runtime:$lifecycle_version"
implementation "androidx.lifecycle:lifecycle-common-java8:$lifecycle_version"
implementation "androidx.lifecycle:lifecycle-process:$lifecycle_version"
```

这三个都是安卓官方库，我自己的app里也因为涉及到应用生命周期的功能而不得不引用上述库。
所以麻烦技术人员看到后能够解决

**Comment by l12ab** [comment]
临时方案，把lifecycle_version降级到2.2.0

**Comment by l12ab** [comment]
https://android.googlesource.com/platform/frameworks/support/+/a9a8ffd7d455ff81f81f5c71bb300b6acab823ba%5E%21/#F18

**Comment by Petterpx** [comment]
+1
