### ISSUE TITLE
tinker 下发patch成功之后杀死应用后patch包失效

### ISSUE THREAD

**Issue by cyf1161265793** [BuglyDevTeam/Bugly-Android-Demo#313]

**Comment by gyf-dev** [comment]
+1

**Comment by linzhongshu** [comment]
参照 #1566 试试

> #### 异常类型
> app运行时异常
> 
> #### 手机型号
> 华为mate10
> 
> #### 手机系统版本
> EMUI8.0
> 
> #### Tinker版本
> tinker-support版本1.2.1、crashreport_update版本1.4.2、tinker-android-lib:1.9.14.7
> 
> #### gradle版本
> gradle:3.5.2
> 
> #### 系统
> Android
> 
> #### 堆栈/日志
> 2021-05-24 17:17:22.915 8226-8226/ E/Tinker.DefaultLoadReporter: tinker load exception com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:checkDexInstall failed
> at com.tencent.tinker.loader.SystemClassLoaderAdder.installDexes(SystemClassLoaderAdder.java:83)
> at com.tencent.tinker.loader.TinkerDexLoader.loadTinkerJars(TinkerDexLoader.java:189)
> at com.tencent.tinker.loader.TinkerLoader.tryLoadPatchFilesInternal(TinkerLoader.java:309)
> at com.tencent.tinker.loader.TinkerLoader.tryLoad(TinkerLoader.java:57)
> at java.lang.reflect.Method.invoke(Native Method)
> at com.tencent.tinker.loader.app.TinkerApplication.loadTinker(TinkerApplication.java:96)
> at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(TinkerApplication.java:136)
> at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(TinkerApplication.java:157)
> at com.tencent.bugly.beta.tinker.TinkerPatchReflectApplication.attachBaseContext(BUGLY:57)
> at android.app.Application.attach(Application.java:189)
> at android.app.Instrumentation.newApplication(Instrumentation.java:1008)
> at android.app.Instrumentation.newApplication(Instrumentation.java:992)
> at android.app.Instrumentation.newApplication(Native Method)
> at android.app.LoadedApk.makeApplication(LoadedApk.java:796)
> at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5456)
> at android.app.ActivityThread.-wrap2(ActivityThread.java)
> at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1548)
> at android.os.Handler.dispatchMessage(Handler.java:102)
> at android.os.Looper.loop(Looper.java:154)
> at android.app.ActivityThread.main(ActivityThread.java:6198)
> at java.lang.reflect.Method.invoke(Native Method)
> at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891)
> at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)
> 
> #### 测试步骤
> 1.生成base包之后安装联网上报
> 2.生成patch包上传bugly
> 3.下发
> 4.出现重启框之后点击重启，应用没有主动打开
> 5.点击桌面icon进入app，测试应用发现patch包已经合成生效
> 6.杀死应用重新进入，patch包失效了

**Comment by linzhongshu** [comment]
参考 https://github.com/Tencent/tinker/issues/1601#issue-989640412 试试

> #### 异常类型
> app运行时异常
> 
> #### 手机型号
> 华为mate10
> 
> #### 手机系统版本
> EMUI8.0
> 
> #### Tinker版本
> tinker-support版本1.2.1、crashreport_update版本1.4.2、tinker-android-lib:1.9.14.7
> 
> #### gradle版本
> gradle:3.5.2
> 
> #### 系统
> Android
> 
> #### 堆栈/日志
> 2021-05-24 17:17:22.915 8226-8226/ E/Tinker.DefaultLoadReporter: tinker load exception com.tencent.tinker.loader.TinkerRuntimeException: Tinker Exception:checkDexInstall failed
> at com.tencent.tinker.loader.SystemClassLoaderAdder.installDexes(SystemClassLoaderAdder.java:83)
> at com.tencent.tinker.loader.TinkerDexLoader.loadTinkerJars(TinkerDexLoader.java:189)
> at com.tencent.tinker.loader.TinkerLoader.tryLoadPatchFilesInternal(TinkerLoader.java:309)
> at com.tencent.tinker.loader.TinkerLoader.tryLoad(TinkerLoader.java:57)
> at java.lang.reflect.Method.invoke(Native Method)
> at com.tencent.tinker.loader.app.TinkerApplication.loadTinker(TinkerApplication.java:96)
> at com.tencent.tinker.loader.app.TinkerApplication.onBaseContextAttached(TinkerApplication.java:136)
> at com.tencent.tinker.loader.app.TinkerApplication.attachBaseContext(TinkerApplication.java:157)
> at com.tencent.bugly.beta.tinker.TinkerPatchReflectApplication.attachBaseContext(BUGLY:57)
> at android.app.Application.attach(Application.java:189)
> at android.app.Instrumentation.newApplication(Instrumentation.java:1008)
> at android.app.Instrumentation.newApplication(Instrumentation.java:992)
> at android.app.Instrumentation.newApplication(Native Method)
> at android.app.LoadedApk.makeApplication(LoadedApk.java:796)
> at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5456)
> at android.app.ActivityThread.-wrap2(ActivityThread.java)
> at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1548)
> at android.os.Handler.dispatchMessage(Handler.java:102)
> at android.os.Looper.loop(Looper.java:154)
> at android.app.ActivityThread.main(ActivityThread.java:6198)
> at java.lang.reflect.Method.invoke(Native Method)
> at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891)
> at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)
> 
> #### 测试步骤
> 1.生成base包之后安装联网上报
> 2.生成patch包上传bugly
> 3.下发
> 4.出现重启框之后点击重启，应用没有主动打开
> 5.点击桌面icon进入app，测试应用发现patch包已经合成生效
> 6.杀死应用重新进入，patch包失效了
