### ISSUE TITLE
BuglyHotfixDemo 检查不到更新

### ISSUE THREAD

**Issue by huhuang03** [BuglyDevTeam/Bugly-Android-Demo#350]
按照官方例子，成功在bugly后台上传补丁包。但是app检查更新的时候报错了。好像gzip有关的错误

```
02-25 10:52:00.867 28610 28610 D CrashReport: requestGrayTactics strategyType:[0]
02-25 10:52:00.867 28610 28610 D CrashReport: requestGrayTactics1 strategyType:[0]
02-25 10:52:00.868 28610 28610 D CrashReport: requestGrayTactics2 strategyType:[0]
02-25 10:52:00.869 28610 28610 D CrashReport: app version is: [2.0.3], [deviceId:2a2c07165fd87a45], channel: [null], buildNo: [0], base tinkerId:[2.0.3_0225-10-36-10], patch tinkerId:[], patch version:[], strategyType:[0]
02-25 10:52:00.869 28610 28610 D CrashReport: [UploadManager] Add upload task (pid=28610 | tid=28610)
02-25 10:52:00.869 28610 28610 D CrashReport: [UploadManager] Add upload task to queue (pid=28610 | tid=28610)
02-25 10:52:00.869 28610 28610 D CrashReport: [UploadManager] Try to poll all upload task need and put them into temp queue (pid=28610 | tid=28610)
02-25 10:52:00.869 28610 28610 D CrashReport: [UploadManager] Execute urgent upload tasks of queue which has 1 tasks (pid=28610 | tid=28610)
02-25 10:52:00.869 28610 28610 I CrashReport: [UploadManager] Create and start a new thread to execute a upload task: BUGLY_ASYNC_UPLOAD
02-25 10:52:00.870 28610 28610 D CrashReport: [AsyncTaskHandler] Post a normal task: com.tencent.bugly.proguard.T$b
02-25 10:52:00.872 28610 30171 D CrashReport: [Upload] Run upload task with cmd: 804
02-25 10:52:00.872 28610 30171 D CrashReport: [Util] Zip 726 bytes data with type Gzip
02-25 10:52:00.899 28610 30171 D CrashReport: [Database] deleted t_lr data 1
02-25 10:52:00.915 28610 30171 D CrashReport: [Database] insert t_lr success.
02-25 10:52:00.916 28610 30171 D CrashReport: [UploadManager] Uploading(ID:1002) time: 2022-02-25 10:52:00
02-25 10:52:00.916 28610 30171 D CrashReport: [Upload] Send 566 bytes
02-25 10:52:00.916 28610 30171 D CrashReport: [Upload] Upload to https://android.bugly.qq.com/rqd/async?aid=9cf140ed-5c04-49ff-a4d7-505b8d810d50 with cmd 804 (pid=28610 | tid=30171).
02-25 10:52:00.916 28610 30171 D CrashReport: request: https://android.bugly.qq.com/rqd/async?aid=9cf140ed-5c04-49ff-a4d7-505b8d810d50, send: 566 (pid=28610 | tid=30171)
02-25 10:52:00.978 28610 30171 D CrashReport: checkServerTrusted
02-25 10:52:01.059 28610 30171 D CrashReport: [Upload] Bugly version from headers is: bugly/1.0
02-25 10:52:01.059 28610 30171 D CrashReport: [Upload] Status from server is 0 (pid=28610 | tid=30171).
02-25 10:52:01.059 28610 30171 D CrashReport: [Upload] Received 158 bytes
02-25 10:52:01.059 28610 30171 D CrashReport: [Util] Unzip 158 bytes data with type Gzip
02-25 10:52:01.059 28610 30171 W CrashReport: java.io.IOException: unknown format (magic number 0)
02-25 10:52:01.059 28610 30171 W CrashReport: 	at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:109)
02-25 10:52:01.059 28610 30171 W CrashReport: 	at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:88)
02-25 10:52:01.059 28610 30171 W CrashReport: 	at com.tencent.bugly.proguard.ia.b(Unknown Source)
02-25 10:52:01.059 28610 30171 W CrashReport: 	at com.tencent.bugly.proguard.ca.a(Unknown Source)
02-25 10:52:01.059 28610 30171 W CrashReport: 	at com.tencent.bugly.proguard.U.run(Unknown Source)
02-25 10:52:01.059 28610 30171 W CrashReport: 	at com.tencent.bugly.proguard.T$a.run(Unknown Source)
02-25 10:52:01.059 28610 30171 W CrashReport: 	at java.lang.Thread.run(Thread.java:818)
02-25 10:52:01.059 28610 30171 D CrashReport: [Upload] Response cmd is: 0, length of sBuffer is: 0
02-25 10:52:01.059 28610 30171 I CrashReport: [Upload] Success: 804
02-25 10:52:01.061 28610 30171 D CrashReport: [UploadManager] Local network consume: 11 KB
02-25 10:52:01.071 28610 30171 D CrashReport: [Database] deleted t_lr data 1
02-25 10:52:01.081 28610 30171 D CrashReport: [Database] insert t_lr success.
02-25 10:52:01.081 28610 30171 D CrashReport: [UploadManager] Network total consume: 12 KB
02-25 10:52:01.081 28610 30171 I CrashReport: upload succ:[804] [sended 566] [recevied 158]
```

而且我点击手动下载补丁包，没有任何日志输出。

**Comment by huhuang03** [comment]
而且我点击手动下载补丁包，没有任何日志输出。

**Comment by huhuang03** [comment]
过了大概10分钟，能够检查到补丁了！！
