### ISSUE TITLE
热修复，补丁包下发成功后，重启应用报异常：Missing android.support.FILE_PROVIDER_PATHS meta-data 

### ISSUE THREAD

**Issue by zhuanglee** [BuglyDevTeam/Bugly-Android-Demo#37]
![image](https://user-images.githubusercontent.com/15305926/33918613-530cfa56-dfef-11e7-8e66-1614b43397c2.png)

12-12 15:10:44.411 7051-7051/? W/ResourceType: Failure getting entry for 0x7f090001 (t=8 e=1) (error -2147483647)
12-12 15:10:44.412 7051-7051/? W/PackageManager: Failure retrieving xml 0x7f090001 in package ***
                                                 android.content.res.Resources$NotFoundException: Resource ID #0x7f090001
                                                     at android.content.res.Resources.getValue(Resources.java:1266)
                                                     at android.content.res.Resources.loadXmlResourceParser(Resources.java:2649)
                                                     at android.content.res.Resources.getXml(Resources.java:1131)
                                                     at android.app.ApplicationPackageManager.getXml(ApplicationPackageManager.java:1178)
                                                     at android.content.pm.PackageItemInfo.loadXmlMetaData(PackageItemInfo.java:279)
                                                     at android.support.v4.content.FileProvider.parsePathStrategy(FileProvider.java:584)
                                                     at android.support.v4.content.FileProvider.getPathStrategy(FileProvider.java:558)
                                                     at android.support.v4.content.FileProvider.attachInfo(FileProvider.java:376)
                                                     at android.app.ActivityThread.installProvider(ActivityThread.java:4999)
                                                     at android.app.ActivityThread.installContentProviders(ActivityThread.java:4594)
                                                     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4534)
                                                     at android.app.ActivityThread.access$1500(ActivityThread.java:151)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1364)
                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                     at android.os.Looper.loop(Looper.java:135)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5254)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at java.lang.reflect.Method.invoke(Method.java:372)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:902)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:697)
12-12 15:10:44.412 7051-7051/? D/AndroidRuntime: Shutting down VM
12-12 15:10:44.412 7051-7051/? E/Tinker.TinkerUncaughtExceptionHandler: uncaughtException:Unable to get provider com.tencent.bugly.beta.utils.BuglyFileProvider: java.lang.IllegalArgumentException: Missing android.support.FILE_PROVIDER_PATHS meta-data
12-12 15:10:44.418 7051-7051/? E/Tinker.TinkerUncaughtExceptionHandler: tinker has fast crash 2 times
12-12 15:10:44.418 7051-7051/? E/Tinker.UncaughtHandler: TinkerUncaughtHandler catch exception:java.lang.RuntimeException: Unable to get provider com.tencent.bugly.beta.utils.BuglyFileProvider: java.lang.IllegalArgumentException: Missing android.support.FILE_PROVIDER_PATHS meta-data
                                                             at android.app.ActivityThread.installProvider(ActivityThread.java:5002)
                                                             at android.app.ActivityThread.installContentProviders(ActivityThread.java:4594)
                                                             at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4534)
                                                             at android.app.ActivityThread.access$1500(ActivityThread.java:151)
                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1364)
                                                             at android.os.Handler.dispatchMessage(Handler.java:102)
                                                             at android.os.Looper.loop(Looper.java:135)
                                                             at android.app.ActivityThread.main(ActivityThread.java:5254)
                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                             at java.lang.reflect.Method.invoke(Method.java:372)
                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:902)
                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:697)
                                                          Caused by: java.lang.IllegalArgumentException: Missing android.support.FILE_PROVIDER_PATHS meta-data
                                                             at android.support.v4.content.FileProvider.parsePathStrategy(FileProvider.java:587)
                                                             at android.support.v4.content.FileProvider.getPathStrategy(FileProvider.java:558)
                                                             at android.support.v4.content.FileProvider.attachInfo(FileProvider.java:376)
                                                             at android.app.ActivityThread.installProvider(ActivityThread.java:4999)
                                                             at android.app.ActivityThread.installContentProviders(ActivityThread.java:4594) 
                                                             at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4534) 
                                                             at android.app.ActivityThread.access$1500(ActivityThread.java:151) 
                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1364) 
                                                             at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                             at android.os.Looper.loop(Looper.java:135) 
                                                             at android.app.ActivityThread.main(ActivityThread.java:5254) 
                                                             at java.lang.reflect.Method.invoke(Native Method) 
                                                             at java.lang.reflect.Method.invoke(Method.java:372) 
                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:902) 
                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:697)

**Comment by zhuanglee** [comment]
截图仅仅是设备信息，因为在启动应用时就报错，并没有上传到bugly

**Comment by devilWwj** [comment]
你好，可能跟ide有关，可以手动添加fileProvider来解决问题

**Comment by liulance** [comment]
@devilWwj 您好，我集成bugly tinker ,打修复包的时候，总是报
![image](https://user-images.githubusercontent.com/22095781/38591181-0aab0e8e-3d68-11e8-84e4-f53ff2013514.png)
这个问题，您知道是什么原因吗？谢谢

**Comment by devilWwj** [comment]
你好，这个是网络的问题导致的，检查下是否开了代理

**Comment by zhuanglee** [comment]
我这个问题是因为当时修改了清单文件，导致合并补丁包后出错
