### ISSUE TITLE
Process: com.tencent.bugly.hotfix.easy异常

### ISSUE THREAD

**Issue by iamjiangyong** [BuglyDevTeam/Bugly-Android-Demo#54]
04-04 17:43:18.917 3402-3402/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                 Process: com.tencent.bugly.hotfix.easy, PID: 3402
                                                 java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
                                                     at com.tencent.bugly.hotfix.easy.BugClass.bug(Unknown Source)
                                                     at com.tencent.bugly.hotfix.easy.LoadBugClass.getBugString(Unknown Source)
                                                     at com.tencent.bugly.hotfix.easy.MainActivity.testToast(Unknown Source)
                                                     at com.tencent.bugly.hotfix.easy.MainActivity.onClick(Unknown Source)
                                                     at android.view.View.performClick(View.java:5623)
                                                     at android.view.View$PerformClick.run(View.java:22433)
                                                     at android.os.Handler.handleCallback(Handler.java:751)
                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                     at android.os.Looper.loop(Looper.java:154)
                                                     at android.app.ActivityThread.main(ActivityThread.java:6247)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:872)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762)
这个栈已知在log错误

**Comment by devilWwj** [comment]
你好，这是测试demo，空指针异常，为了让你们测试修复的
