### ISSUE TITLE
引入Tinker之后如何在Debug模式下开启Instant Run？

### ISSUE THREAD

**Issue by vincgao** [BuglyDevTeam/Bugly-Android-Demo#8]
关闭Instant Run，App引入Bugly的热更新，已经运行起来，并且可以通过下发补丁修复成功。
我想在debug开发模式下开启Instant Run。做了如下尝试：
1. 在tinker-support.gradle设置enable = false，gradle提示需要关闭Instant Run或者命令行打包
2. 不引入tinker-support.gradle配置，在开启Instant Run状态下，点Android Studio运行按钮运行成功，但App马上崩溃。信息如下
ps：方法2原理和[Tinker wiki](https://github.com/Tencent/tinker/wiki/Tinker-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#tinker%E4%B8%8Einstant-run%E7%9A%84%E5%85%BC%E5%AE%B9%E9%97%AE%E9%A2%98)给出的解决办法应该是一样的。不知为何在bugly配置里这种修改并不work
```
02-17 18:44:12.219 7423-7423/? E/AndroidRuntime: FATAL EXCEPTION: main
     java.lang.RuntimeException: Unable to instantiate application com.android.tools.fd.runtime.BootstrapApplication: java.lang.IllegalStateException: java.lang.NoSuchMethodException: <init> []
         at android.app.LoadedApk.makeApplication(LoadedApk.java:616)
         at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5033)
         at android.app.ActivityThread.access$1500(ActivityThread.java:186)
         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1635)
         at android.os.Handler.dispatchMessage(Handler.java:111)
         at android.os.Looper.loop(Looper.java:192)
         at android.app.ActivityThread.main(ActivityThread.java:5865)
         at java.lang.reflect.Method.invoke(Native Method)
         at java.lang.reflect.Method.invoke(Method.java:372)
         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1021)
         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:816)
      Caused by: java.lang.IllegalStateException: java.lang.NoSuchMethodException: <init> []
         at com.android.tools.fd.runtime.BootstrapApplication.createRealApplication(BootstrapApplication.java:220)
         at com.android.tools.fd.runtime.BootstrapApplication.attachBaseContext(BootstrapApplication.java:239)
         at android.app.Application.attach(Application.java:181)
         at android.app.Instrumentation.newApplication(Instrumentation.java:1017)
         at android.app.Instrumentation.newApplication(Instrumentation.java:1001)
         at android.app.LoadedApk.makeApplication(LoadedApk.java:611)
         at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5033) 
         at android.app.ActivityThread.access$1500(ActivityThread.java:186) 
         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1635) 
         at android.os.Handler.dispatchMessage(Handler.java:111) 
         at android.os.Looper.loop(Looper.java:192) 
         at android.app.ActivityThread.main(ActivityThread.java:5865) 
         at java.lang.reflect.Method.invoke(Native Method) 
         at java.lang.reflect.Method.invoke(Method.java:372) 
         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1021) 
         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:816) 
      Caused by: java.lang.NoSuchMethodException: <init> []
         at java.lang.Class.getConstructor(Class.java:531)
         at java.lang.Class.getConstructor(Class.java:495)
         at com.android.tools.fd.runtime.BootstrapApplication.createRealApplication(BootstrapApplication.java:214)
         at com.android.tools.fd.runtime.BootstrapApplication.attachBaseContext(BootstrapApplication.java:239) 
         at android.app.Application.attach(Application.java:181) 
         at android.app.Instrumentation.newApplication(Instrumentation.java:1017) 
         at android.app.Instrumentation.newApplication(Instrumentation.java:1001) 
         at android.app.LoadedApk.makeApplication(LoadedApk.java:611) 
         at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5033) 
         at android.app.ActivityThread.access$1500(ActivityThread.java:186) 
         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1635) 
         at android.os.Handler.dispatchMessage(Handler.java:111) 
         at android.os.Looper.loop(Looper.java:192) 
         at android.app.ActivityThread.main(ActivityThread.java:5865) 
         at java.lang.reflect.Method.invoke(Native Method) 
         at java.lang.reflect.Method.invoke(Method.java:372) 
         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1021) 
         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:816) 
```

**Comment by devilWwj** [comment]
你好，ext只是扩展参数的配置，你要针对插件的进行关闭，如果你平时开发使用instant run，只需要将apply from 'tinker-support.gradle'这一句注释掉即可。

**Comment by vincgao** [comment]
注释掉apply from: 'tinker-support.gradle'之后报了上面的那个错误 😕

**Comment by linyuwuyun** [comment]
使用反射Application方式接入：可以直接在build.gradle中将apply from: 'tinker-support.gradle'注释掉。
改造Application方式接入：先将tinkerSupport中overrideTinkerPatchConfiguration设置为false，然后将tinkerPatch中的tinkerEnable设置为false。

**Comment by nkbaer** [comment]
并不管用，按照 “改造Application方式接入：先将tinkerSupport中overrideTinkerPatchConfiguration设置为false，然后将tinkerPatch中的tinkerEnable设置为false。” 会报“Cause: tinkerId is not set!!!” 错误。

**Comment by honglei92** [comment]
1.public class BaseApplication extends Application 换回以前的
2.//apply from: 'tinker-support.gradle'注释掉
3.//classpath "com.tencent.bugly:tinker-support:1.1.2"注释掉

**Comment by jeonhei** [comment]
> 使用反射Application方式接入：可以直接在build.gradle中将apply from: 'tinker-support.gradle'注释掉。
> 改造Application方式接入：先将tinkerSupport中overrideTinkerPatchConfiguration设置为false，然后将tinkerPatch中的tinkerEnable设置为false。

这是正解 如果用了改造application的模式需要临时关闭tinker的话还需要在tinkerPatch里添加tinkerEnable = false 不知道腾讯搞什么的 17年头的问题到现在18年都过去一大半了还没更新文档!

**Comment by dede1314** [comment]
> 并不管用，按照 “改造Application方式接入：先将tinkerSupport中overrideTinkerPatchConfiguration设置为false，然后将tinkerPatch中的tinkerEnable设置为false。” 会报“Cause: tinkerId is not set!!!” 错误。

还需要将tinker.gradle中的tinkerPatch闭包中的buildConfig下面的tinkerId = "1.0.1-base"这句打开注释。
现在能正常编译成功，但还是不能使用instant run。
