### ISSUE TITLE
使用enableProxyApplication = true 集成报错

### ISSUE THREAD

**Issue by ty44795016** [BuglyDevTeam/Bugly-Android-Demo#9]
使用反射生成application的方式集成，执行assembleRelease生成基线包，安装后报错堆栈如下： 
 java.lang.RuntimeException: Unable to instantiate application com.tencent.bugly.beta.tinker.TinkerPatchReflectApplication: java.lang.ClassNotFoundException: Didn't find class "com.tencent.bugly.beta.tinker.TinkerPatchReflectApplication" on path: DexPathList[[zip file "/data/app/{packagename}/base.apk"],nativeLibraryDirectories=[/data/app/{packagename}/lib/arm, /vendor/lib, /system/lib]]
                                                       at android.app.LoadedApk.makeApplication(LoadedApk.java:612)
                                                       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4672)
                                                       at android.app.ActivityThread.access$1500(ActivityThread.java:162)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1409)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:135)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5421)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:372)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:914)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:707)
                                                    Caused by: java.lang.ClassNotFoundException: Didn't find class "com.tencent.bugly.beta.tinker.TinkerPatchReflectApplication" on path: DexPathList[[zip file "/data/app/{packagename}/base.apk"],nativeLibraryDirectories=[/data/app/{packagename}/lib/arm, /vendor/lib, /system/lib]]
                                                       at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                       at android.app.Instrumentation.newApplication(Instrumentation.java:980)
                                                       at android.app.LoadedApk.makeApplication(LoadedApk.java:607)
                                                       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4672) 
                                                       at android.app.ActivityThread.access$1500(ActivityThread.java:162) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1409) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:135) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5421) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at java.lang.reflect.Method.invoke(Method.java:372) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:914) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:707) 
                                                   	Suppressed: java.lang.ClassNotFoundException: com.tencent.bugly.beta.tinker.TinkerPatchReflectApplication
                                                       at java.lang.Class.classForName(Native Method)
                                                       at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                                       at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:504)

**Comment by devilWwj** [comment]
请将系统版本，测试环境等信息提供给我们

**Comment by devilWwj** [comment]
请按照issue提问规则来提问：https://github.com/BuglyDevTeam/Bugly-Android-Demo/issues/16

**Comment by wcrhjc123** [comment]
我这碰到了个同样的问题。请问。是怎么解决的啊？

**Comment by cfm1120** [comment]
我也是一样的问题 请问怎么解决

**Comment by Eric3023** [comment]
我也是一样的问题 请问怎么解决
