### ISSUE TITLE
java.io.FileNotFoundException: /system/build.prop (Permission denied)

### ISSUE THREAD

**Issue by feng88724** [BuglyDevTeam/Bugly-Android-Demo#92]
#### 异常类型
FileNotFoundException

#### 手机型号
Huawei P9

#### 手机系统版本
Android 8.0

#### gradle版本
2.2.0

#### 系统
Mac

#### 堆栈/日志
CrashReport: java.io.FileNotFoundException: /system/build.prop (Permission denied)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:200)
        at java.io.FileInputStream.<init>(FileInputStream.java:150)
        at java.io.FileInputStream.<init>(FileInputStream.java:103)
        at java.io.FileReader.<init>(FileReader.java:58)
        at com.tencent.bugly.crashreport.common.info.b.q(BUGLY:320)
        at com.tencent.bugly.crashreport.common.info.b.a(BUGLY:379)
        at com.tencent.bugly.crashreport.common.info.a.r(BUGLY:509)
        at com.tencent.bugly.proguard.a.a(BUGLY:160)
        at com.tencent.bugly.crashreport.biz.a.c(BUGLY:271)
        at com.tencent.bugly.crashreport.biz.a.a(BUGLY:35)
        at com.tencent.bugly.crashreport.biz.a$2.run(BUGLY:335)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:784)

#### 复现路径
启动日志上报就可以看到了

**Comment by JalenChen** [comment]
该问题不会影响正常使用，另建议更新SDK到最新版。
